# Generated by Django 3.0.3 on 2020-03-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200319_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
